class Assistant:
    def __init__(self, api_key, model, temperature, retry_limit):
        """
        Create a llm assistant with given model and temperature.

        Parameters:
            api_key - Api key of SiliconFlow.
            model - name of the model to be called.
            temperature - temperature set by the model.
            retry_limit - maximum number of retries if network error occurs.
        """
        pass
    
    def chat(self, messages):
        """
        Generate a response of given context.

        Parameters:
            messages - a list of previous conversation. Each message
                should follow the format { "role": "user" / "assistant",
                "content": <content>}.
        
        Returns:
            Response generated by llm.

        Raises:
            ApiError(code) - response has an unsuccessful status code, after
                retry_limit retries.
        """
        pass